-- Heatmap tracking table: click coordinates and scroll depth, captured
-- client-side on the public JP Infra site and read back by the admin
-- dashboard. Run this once in the Supabase SQL Editor.

create table if not exists public.heatmap_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  page text not null check (
    page in (
      'home',
      'explore',
      'panorama',
      'gallery',
      'about',
      'contact',
      'floorplans',
      'amenities'
    )
  ),
  device_type text not null check (
    device_type in ('desktop', 'tablet', 'mobile')
  ),
  event_type text not null check (
    event_type in ('click', 'scroll')
  ),
  x_pct numeric(5, 2),
  y_pct numeric(5, 2),
  viewport_width integer not null,
  viewport_height integer not null,
  scroll_depth integer,
  constraint heatmap_events_payload_matches_type check (
    (event_type = 'click' and x_pct is not null and y_pct is not null)
    or
    (event_type = 'scroll' and scroll_depth is not null)
  )
);

create index if not exists heatmap_events_page_device_type_idx
  on public.heatmap_events (page, device_type, event_type);

create index if not exists heatmap_events_created_at_idx
  on public.heatmap_events (created_at);

alter table public.heatmap_events enable row level security;

-- The public site writes with the anon/publishable key — insert only, no
-- read/update/delete access, so visitors can never see each other's data.
drop policy if exists "Anon can insert heatmap events" on public.heatmap_events;
create policy "Anon can insert heatmap events"
  on public.heatmap_events
  for insert
  to anon
  with check (true);

-- The admin dashboard reads as a logged-in Supabase Auth user.
drop policy if exists "Authenticated users can read heatmap events" on public.heatmap_events;
create policy "Authenticated users can read heatmap events"
  on public.heatmap_events
  for select
  to authenticated
  using (true);
